### PR TITLE
updating dependencies

### PR DESCRIPTION
**Pull request by yannikbehr**
Hi @liamtoney, I've been having a hard time getting the environment setup for your ashfall visualizations. The modifications I've made now allow me to do 

```
conda env create -f environment.yml
```
and then run your concept_portfolio notbook. Can you have a quick look at the changes and merge if you are happy with it or let me know if you don't like it? I haven't tried it with mybinder yet.

### CODE REVIEW

**Comment by liamtoney** [comment]
Thanks for letting me know, @yannikbehr. I think having fewer dependencies ought to help, rather than hurt, the Binder build. My main question is how do we get Bokeh? Is it wrapped into PyViz?

**Comment by liamtoney** [comment]
I tried paring down `environment.yml` even further. I've adjusted all of the code to run with the updated packages. Can you go ahead and try things out on your end with the new `environment.yml`?

**Comment by yannikbehr** [comment]
Oops, sorry for the late reply @liamtoney. For some reason I didn't receive an email on your update. I'll have a look at this tomorrow.

**Comment by yannikbehr** [comment]
I just tested your latest changes and it works like a charm. I will close this pull request.

**Comment by liamtoney** [comment]
Great!

**Pull request closed without merging**
